<script lang="ts">
  import { goto } from '$app/navigation';
  import type { Checkpoint } from '$lib/types';

  let name = '';
  let description = '';
  let template = 'standard-6-phase';
  let phaseOrder = 'neurons_first';
  let gaGenerations = 250;
  let tsIterations = 250;
  let populationSize = 50;
  let patience = 10;
  let seedCheckpointId: number | null = null;

  let checkpoints: Checkpoint[] = [];
  let loading = false;
  let error: string | null = null;

  // Fetch available checkpoints for seeding
  async function loadCheckpoints() {
    try {
      const response = await fetch('/api/checkpoints?is_final=true&limit=50');
      if (response.ok) {
        checkpoints = await response.json();
      }
    } catch (e) {
      console.error('Failed to load checkpoints:', e);
    }
  }

  loadCheckpoints();

  async function handleSubmit() {
    if (!name.trim()) {
      error = 'Name is required';
      return;
    }

    loading = true;
    error = null;

    try {
      const response = await fetch('/api/flows', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          description: description || null,
          config: {
            experiments: [], // Will be generated by backend based on template
            template,
            params: {
              phase_order: phaseOrder,
              ga_generations: gaGenerations,
              ts_iterations: tsIterations,
              population_size: populationSize,
              patience
            }
          },
          seed_checkpoint_id: seedCheckpointId
        })
      });

      if (!response.ok) {
        throw new Error('Failed to create flow');
      }

      const flow = await response.json();
      goto(`/flows/${flow.id}`);
    } catch (e) {
      error = e instanceof Error ? e.message : 'Unknown error';
    } finally {
      loading = false;
    }
  }
</script>

<div class="container">
  <div class="page-header">
    <a href="/flows" class="back-link">&larr; Flows</a>
    <h1>New Flow</h1>
  </div>

  <form on:submit|preventDefault={handleSubmit} class="form">
    {#if error}
      <div class="error-message">{error}</div>
    {/if}

    <div class="form-section">
      <h2>Basic Info</h2>

      <div class="form-group">
        <label for="name">Name *</label>
        <input
          type="text"
          id="name"
          bind:value={name}
          placeholder="e.g., Pass 1 - Initial Search"
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <textarea
          id="description"
          bind:value={description}
          placeholder="Optional description..."
          rows="3"
        ></textarea>
      </div>
    </div>

    <div class="form-section">
      <h2>Configuration</h2>

      <div class="form-row">
        <div class="form-group">
          <label for="template">Template</label>
          <select id="template" bind:value={template}>
            <option value="standard-6-phase">Standard 6-Phase</option>
          </select>
        </div>

        <div class="form-group">
          <label for="phaseOrder">Phase Order</label>
          <select id="phaseOrder" bind:value={phaseOrder}>
            <option value="neurons_first">Neurons First</option>
            <option value="bits_first">Bits First</option>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group">
          <label for="gaGens">GA Generations</label>
          <input type="number" id="gaGens" bind:value={gaGenerations} min="1" />
        </div>

        <div class="form-group">
          <label for="tsIters">TS Iterations</label>
          <input type="number" id="tsIters" bind:value={tsIterations} min="1" />
        </div>
      </div>

      <div class="form-row">
        <div class="form-group">
          <label for="popSize">Population Size</label>
          <input type="number" id="popSize" bind:value={populationSize} min="1" />
        </div>

        <div class="form-group">
          <label for="patience">Patience</label>
          <input type="number" id="patience" bind:value={patience} min="1" />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h2>Seed Checkpoint (Optional)</h2>
      <p class="section-hint">
        Select a checkpoint to seed the first experiment from a previous run.
      </p>

      <div class="form-group">
        <label for="seedCheckpoint">Seed From</label>
        <select id="seedCheckpoint" bind:value={seedCheckpointId}>
          <option value={null}>No seed (start fresh)</option>
          {#each checkpoints as ckpt}
            <option value={ckpt.id}>
              {ckpt.name}
              {#if ckpt.final_fitness}
                (CE: {ckpt.final_fitness.toFixed(4)})
              {/if}
            </option>
          {/each}
        </select>
      </div>
    </div>

    <div class="form-actions">
      <a href="/flows" class="btn btn-secondary">Cancel</a>
      <button type="submit" class="btn btn-primary" disabled={loading}>
        {loading ? 'Creating...' : 'Create Flow'}
      </button>
    </div>
  </form>
</div>

<style>
  .page-header {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 2rem;
    padding-top: 2rem;
  }

  .back-link {
    color: var(--text-secondary);
    text-decoration: none;
    font-size: 0.875rem;
  }

  .back-link:hover {
    color: var(--text-primary);
  }

  h1 {
    font-size: 1.5rem;
    font-weight: 600;
    color: var(--text-primary);
    margin: 0;
  }

  .form {
    max-width: 600px;
  }

  .form-section {
    background: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
  }

  h2 {
    font-size: 1rem;
    font-weight: 600;
    color: var(--text-primary);
    margin: 0 0 1rem 0;
  }

  .section-hint {
    font-size: 0.875rem;
    color: var(--text-secondary);
    margin: -0.5rem 0 1rem 0;
  }

  .form-group {
    margin-bottom: 1rem;
  }

  .form-group:last-child {
    margin-bottom: 0;
  }

  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
  }

  label {
    display: block;
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--text-primary);
    margin-bottom: 0.375rem;
  }

  input, select, textarea {
    width: 100%;
    padding: 0.5rem 0.75rem;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--bg-primary);
    color: var(--text-primary);
    font-size: 0.875rem;
    font-family: inherit;
  }

  input:focus, select:focus, textarea:focus {
    outline: none;
    border-color: var(--accent-blue);
  }

  textarea {
    resize: vertical;
  }

  .form-actions {
    display: flex;
    gap: 1rem;
    justify-content: flex-end;
  }

  .btn {
    padding: 0.5rem 1rem;
    border-radius: 6px;
    font-size: 0.875rem;
    font-weight: 500;
    text-decoration: none;
    border: none;
    cursor: pointer;
    transition: all 0.2s;
  }

  .btn-primary {
    background: var(--accent-blue);
    color: white;
  }

  .btn-primary:hover:not(:disabled) {
    opacity: 0.9;
  }

  .btn-primary:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .btn-secondary {
    background: var(--bg-tertiary);
    color: var(--text-primary);
  }

  .btn-secondary:hover {
    background: var(--border);
  }

  .error-message {
    background: rgba(239, 68, 68, 0.1);
    border: 1px solid var(--accent-red);
    color: var(--accent-red);
    padding: 0.75rem 1rem;
    border-radius: 6px;
    font-size: 0.875rem;
    margin-bottom: 1rem;
  }
</style>
