#!/usr/bin/env python3
"""Generate mcu/ids_model.h — an IDS-shaped WNN model for the MCU cost harness.

WHY SYNTHETIC KEYS ARE LEGITIMATE HERE, and where they are not.

We are measuring the INSTRUCTION COST of one classification, and that cost is
determined by the model's SHAPE, not by which addresses happen to be populated:

  gather  = neurons x bits            load/shift/or per address bit   -- shape only
  search  = neurons x ceil(log2 k)    the loop runs to convergence with no early
                                      exit, so a hit and a miss cost identically
                                      (this is the bounded-WCET property the FPGA
                                      claim already rests on -- see mcu/README.md)
  score   = neurons                   one conditional add per neuron

So random sorted keys give the same instruction count as trained ones. What they
do NOT give is anything about ACCURACY -- this harness must never be used to say
what an IDS model detects, only what one decision costs.

The shapes themselves are real: 400x34 is a live genome from the flows DB, 500x34
is the shape Vivado synthesised, 250x100 is the production winner, 53x48 is what
the GA picks. Keys-per-neuron is swept rather than assumed, because the DB's
materialized_cells column is unpopulated for architecture_type='ids'.

ADDRESS WIDTH follows ram_core exactly:
  bits <= 32   -> uint32_t key
  bits <= 64   -> uint64_t key   (2 words on a 32-bit M4: compares cost double)
  bits >  64   -> gather into two words, splitmix64 -> uint64_t key
                  (the 29/08 address fix; the old code OR-folded slot i and i+64
                  onto one address bit, which is why >64-bit winners were re-run)
"""
import argparse, random

ap = argparse.ArgumentParser()
ap.add_argument("--neurons", type=int, required=True)
ap.add_argument("--bits", type=int, required=True)
ap.add_argument("--keys-per-neuron", type=int, required=True)
ap.add_argument("--features", type=int, default=42)   # UNSW-NB15 feature count
ap.add_argument("--levels", type=int, default=16)     # thermometer levels/feature
ap.add_argument("--out", default="ids_model.h")
ap.add_argument("--seed", type=int, default=1234)
a = ap.parse_args()

rng = random.Random(a.seed)
inbits = a.features * a.levels
keytype = "uint32_t" if a.bits <= 32 else "uint64_t"
sfx = "u" if a.bits <= 32 else "ull"

conn = [rng.randrange(inbits) for _ in range(a.neurons * a.bits)]

# Per-neuron sorted key arrays. Distinct within a neuron, as a real ON-set is.
space = (1 << a.bits) if a.bits <= 62 else (1 << 62)
keys, off = [], [0]
for _ in range(a.neurons):
	k = sorted(rng.sample(range(space), min(a.keys_per_neuron, space)))
	keys.extend(k)
	off.append(len(keys))

def arr(name, ctype, vals, per, fmt=str):
	out = [f"static const {ctype} {name}[{len(vals)}] = {{"]
	for i in range(0, len(vals), per):
		out.append("\t" + ",".join(fmt(v) for v in vals[i:i + per]) + ",")
	out.append("};")
	return "\n".join(out)

with open(a.out, "w") as f:
	f.write(f"""/* GENERATED by mcu/gen_ids_model.py -- do not edit.
 * shape: {a.neurons} neurons x {a.bits} bits, {a.keys_per_neuron} keys/neuron,
 *        {a.features} features x {a.levels} thermometer levels = {inbits} input bits
 * Keys are SYNTHETIC: cost is shape-determined (see the module docstring).
 */
#ifndef IDS_MODEL_H
#define IDS_MODEL_H
#include <stdint.h>

#define IDS_NEURONS    {a.neurons}
#define IDS_BITS       {a.bits}
#define IDS_FEATURES   {a.features}
#define IDS_LEVELS     {a.levels}
#define IDS_INPUT_BITS {inbits}
#define IDS_NUM_KEYS   {len(keys)}
#define IDS_KEY_T      {keytype}
#define IDS_WIDE       {1 if a.bits > 64 else 0}

""")
	f.write(arr("ids_conn", "uint16_t", conn, 24) + "\n\n")
	f.write(arr("ids_keys", keytype, keys, 8, lambda v: f"{v}{sfx}") + "\n\n")
	f.write(arr("ids_off", "uint32_t", off, 16, lambda v: f"{v}u") + "\n\n")
	f.write("#endif /* IDS_MODEL_H */\n")

kb = len(keys) * (4 if a.bits <= 32 else 8) / 1024
print(f"{a.neurons}n x {a.bits}b, {a.keys_per_neuron} k/n -> {len(keys)} keys, "
      f"{kb:.0f} KB of keys ({keytype}), {len(conn)*2/1024:.0f} KB of connections")
