// WNN Binary Classifier — Top-level IDS module
//
// Architecture:
//   1. Input buffer receives thermometer-encoded feature vector
//   2. N neurons perform parallel sparse BRAM lookups
//   3. Weighted sum accumulates QUAD_WEIGHTED responses
//   4. Threshold comparison produces binary classification
//
// For IDS binary classification: sum > threshold → attack, else normal
//
// Pipeline: input valid → neurons search (parallel, ~12 cycles) → sum → output valid

module wnn_classifier #(
	parameter int NUM_NEURONS  = 11,
	parameter int INPUT_BITS   = 360,
	parameter int ADDR_BITS    = 34,
	parameter int KEY_BITS     = 64,
	parameter int VALUE_BITS   = 8,
	// Accumulator width: needs to hold NUM_NEURONS * max_weight (3)
	parameter int ACC_BITS     = $clog2(NUM_NEURONS * 3) + 1,
	// Threshold for classification (fixed-point, set by calibration)
	parameter int THRESHOLD    = 0  // Set by RTL generator from calibration
) (
	input  logic                    clk,
	input  logic                    rst_n,
	input  logic                    input_valid,
	input  logic [INPUT_BITS-1:0]   input_vec,

	output logic                    class_out,     // 0=normal, 1=attack
	output logic [ACC_BITS-1:0]     score_out,     // Raw weighted sum
	output logic                    output_valid,
	output logic                    busy
);

	// --- Neuron outputs ---
	logic [VALUE_BITS-1:0] neuron_results [NUM_NEURONS];
	logic [NUM_NEURONS-1:0] neuron_valid;
	logic [NUM_NEURONS-1:0] neuron_busy;
	logic neuron_start;

	// Start all neurons simultaneously
	assign neuron_start = input_valid & !busy;
	assign busy = |neuron_busy;

	// --- Neuron instances (generated by RTL generator) ---
	// Each neuron has its own BRAM and connection map
	// The RTL generator creates wnn_classifier_impl.sv with actual instances

	// --- Accumulation ---
	// When all neurons are done, compute weighted sum
	// QUAD_WEIGHTED: FALSE=0.0, WEAK_FALSE=0.25, WEAK_TRUE=0.75, TRUE=1.0
	// In fixed-point (×4): FALSE=0, WEAK_FALSE=1, WEAK_TRUE=3, TRUE=4
	// So we accumulate the raw cell values (0,1,2,3) as the score

	logic all_valid;
	assign all_valid = &neuron_valid;

	logic [ACC_BITS-1:0] weighted_sum;
	always_comb begin
		weighted_sum = '0;
		for (int i = 0; i < NUM_NEURONS; i++) begin
			weighted_sum = weighted_sum + ACC_BITS'(neuron_results[i]);
		end
	end

	// --- Output registration ---
	always_ff @(posedge clk or negedge rst_n) begin
		if (!rst_n) begin
			class_out    <= 1'b0;
			score_out    <= '0;
			output_valid <= 1'b0;
		end else begin
			output_valid <= 1'b0;
			if (all_valid) begin
				score_out    <= weighted_sum;
				class_out    <= (weighted_sum > ACC_BITS'(THRESHOLD));
				output_valid <= 1'b1;
			end
		end
	end

endmodule
