#!/usr/bin/env python3
"""Emit a controller winner as a self-contained C header for MCU deployment
and benchmarking.

REPRESENTATION. The memory is an ON-SET (every populated cell is TRUE in BINARY
mode), so what ships is a membership test, not a key->value table: per neuron, a
SORTED array of visited addresses, binary-searched at run time. That is the same
representation the IDS FPGA work uses, and the one that fits a Z-7020 (see
project_controller_lut_footprint_b30) -- combinational synthesis of the same
function does not.

Emits:
  wnn_conn[N*B]   input-bit index feeding each neuron's address bit (MSB first)
  wnn_keys[]      all neurons' sorted ON-set addresses, concatenated
  wnn_off[N+1]    start offset per neuron into wnn_keys

Usage:
  PYTHONPATH=src/wnn python scripts/export_controller_c.py \
      --winner <stageN.yaml.gz> --out mcu/wnn_model.h
"""

import argparse
from collections import defaultdict
from pathlib import Path


def parse_args():
	ap = argparse.ArgumentParser(description="Export a controller winner as a C header")
	ap.add_argument("--winner", required=True)
	ap.add_argument("--out", required=True)
	return ap.parse_args()


def emit_array(name: str, ctype: str, values, per_line: int = 16) -> str:
	body = []
	for i in range(0, len(values), per_line):
		body.append("\t" + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
	return (f"static const {ctype} {name}[{len(values)}] = {{\n"
	        + "\n".join(body) + "\n};\n")


def main():
	args = parse_args()
	from wnn.control.checkpoint_io import load_controller_checkpoint
	ckpt = load_controller_checkpoint(args.winner, skip_population=True)
	spec, genome = ckpt["spec"], ckpt["best_genome"]
	bits = int(spec.output_bits_per_neuron)
	motors, levels = int(spec.num_motors), int(spec.levels_per_motor)
	neurons = motors * levels
	# num_features / bits_per_feature are METHODS on ControllerSpec, not fields —
	# int() on the bound method silently reads as a TypeError, not a wrong number.
	nf = spec.num_features() if callable(spec.num_features) else spec.num_features
	bpf = spec.bits_per_feature() if callable(spec.bits_per_feature) else spec.bits_per_feature
	in_bits = int(nf) * int(bpf)

	_, out_conn = genome.to_connections()
	if len(out_conn) != neurons * bits:
		raise SystemExit(f"connection count {len(out_conn)} != {neurons}x{bits}")

	cells = genome.cells
	onsets = defaultdict(list)
	for (n, addr) in cells.output_universe:
		onsets[int(n)].append(int(addr))

	keys, off = [], [0]
	for n in range(neurons):
		keys.extend(sorted(set(onsets.get(n, []))))
		off.append(len(keys))

	hdr = [
		"/* GENERATED by scripts/export_controller_c.py -- do not edit. */",
		f"/* source: {args.winner} */",
		"#ifndef WNN_MODEL_H",
		"#define WNN_MODEL_H",
		"#include <stdint.h>",
		"",
		f"#define WNN_NEURONS   {neurons}",
		f"#define WNN_BITS      {bits}",
		f"#define WNN_MOTORS    {motors}",
		f"#define WNN_LEVELS    {levels}",
		f"#define WNN_INPUT_BITS {in_bits}",
		f"#define WNN_NUM_KEYS  {len(keys)}",
		"",
		emit_array("wnn_conn", "uint8_t", list(out_conn), 24),
		emit_array("wnn_keys", "uint32_t", keys, 12),
		emit_array("wnn_off", "uint32_t", off, 16),
		"#endif /* WNN_MODEL_H */",
	]
	out = Path(args.out)
	out.parent.mkdir(parents=True, exist_ok=True)
	out.write_text("\n".join(hdr) + "\n")
	kb = (len(keys) * 4 + len(out_conn)) / 1024
	print(f"wrote {out}  neurons={neurons} bits={bits} in_bits={in_bits} "
	      f"keys={len(keys)}  (~{kb:.0f} KB of .rodata)")


if __name__ == "__main__":
	main()
