#!/usr/bin/env python3
"""Emit a controller winner as a self-contained C header for MCU deployment
and benchmarking.

REPRESENTATION. What ships is a membership test, not a key->value table: per
neuron, a SORTED array of TRUE addresses, binary-searched at run time.

⚠️ THE ON-SET IS output_values == TRUE, NOT output_universe (fixed 02/09/2026).
A populated cell is NOT necessarily TRUE: BINARY stores both, and
`cell_to_weight` (neuron_memory.rs:113) reads TRUE(1)=1.0 with FALSE, EMPTY and
every stray value alike at 0.0 — i.e. a stored FALSE weighs EXACTLY what a miss
weighs. This exporter used to build the on-set from `output_universe` alone,
which shipped every FALSE cell as a FIRING address: on SL_C_b32n256 that is
196,778 of 1,091,330 cells (18%) inverted, and the header was 18% oversized for
the privilege. Filtering to TRUE is both the correctness fix and the compaction:
a miss and a FALSE agree, so FALSE cells need not be stored at all. That is the same
representation the IDS FPGA work uses, and the one that fits a Z-7020 (see
project_controller_lut_footprint_b30) -- combinational synthesis of the same
function does not.

Emits:
  wnn_conn[N*B]   input-bit index feeding each neuron's address bit (MSB first)
  wnn_keys[]      all neurons' sorted ON-set addresses, concatenated
  wnn_off[N+1]    start offset per neuron into wnn_keys

Usage:
  PYTHONPATH=src/wnn python scripts/export_controller_c.py \
      --winner <stageN.yaml.gz> --out mcu/wnn_model.h
"""

import argparse
from collections import defaultdict
from pathlib import Path

# neuron_memory.rs: FALSE=0, TRUE=1, EMPTY=2. BINARY weighs TRUE 1.0, all else 0.0.
TRUE_CELL = 1


def parse_args():
	ap = argparse.ArgumentParser(description="Export a controller winner as a C header")
	ap.add_argument("--winner", required=True)
	ap.add_argument("--out", required=True)
	return ap.parse_args()


def emit_array(name: str, ctype: str, values, per_line: int = 16) -> str:
	body = []
	for i in range(0, len(values), per_line):
		body.append("\t" + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
	return (f"static const {ctype} {name}[{len(values)}] = {{\n"
	        + "\n".join(body) + "\n};\n")


def true_onset(winner: str) -> dict:
	"""Load a winner checkpoint and build its TRUE-only on-set.

	Returns the geometry plus the concatenated sorted keys and per-neuron
	offsets — everything the C header and the H743 footprint need. Shared with
	scripts/count_true_keys.py so the deployability column and the shipped header
	can never disagree on what a key is.
	"""
	from wnn.control.checkpoint_io import load_controller_checkpoint
	ckpt = load_controller_checkpoint(winner, skip_population=True)
	spec, genome = ckpt["spec"], ckpt["best_genome"]
	bits = int(spec.output_bits_per_neuron)
	motors, levels = int(spec.num_motors), int(spec.levels_per_motor)
	neurons = motors * levels
	# num_features / bits_per_feature are METHODS on ControllerSpec, not fields —
	# int() on the bound method silently reads as a TypeError, not a wrong number.
	nf = spec.num_features() if callable(spec.num_features) else spec.num_features
	bpf = spec.bits_per_feature() if callable(spec.bits_per_feature) else spec.bits_per_feature

	_, out_conn = genome.to_connections()
	if len(out_conn) != neurons * bits:
		raise SystemExit(f"connection count {len(out_conn)} != {neurons}x{bits}")

	cells = genome.cells
	# TRUE-only (02/09/2026). output_universe is every POPULATED cell; the value
	# lives in the parallel output_values array. neuron_memory.rs: BINARY reads
	# TRUE(1)=1.0 and everything else 0.0, so a stored FALSE is indistinguishable
	# from a miss and must NOT be emitted as an on-set member.
	universe = cells.output_universe
	values = cells.output_values
	if len(values) != len(universe):
		raise SystemExit(f"output_values {len(values)} != output_universe {len(universe)}")
	onsets = defaultdict(list)
	n_true = n_false = 0
	for (n, addr), v in zip(universe, values):
		if int(v) == TRUE_CELL:
			onsets[int(n)].append(int(addr))
			n_true += 1
		else:
			n_false += 1

	keys, off = [], [0]
	for n in range(neurons):
		keys.extend(sorted(set(onsets.get(n, []))))
		off.append(len(keys))
	return dict(neurons=neurons, bits=bits, motors=motors, levels=levels,
	            features=int(nf), bits_per_feature=int(bpf), in_bits=int(nf) * int(bpf),
	            conn=list(out_conn), keys=keys, off=off, n_true=n_true, n_false=n_false)


def main():
	args = parse_args()
	m = true_onset(args.winner)
	neurons, bits, motors, levels = m["neurons"], m["bits"], m["motors"], m["levels"]
	nf, bpf, in_bits = m["features"], m["bits_per_feature"], m["in_bits"]
	out_conn, keys, off, n_true, n_false = m["conn"], m["keys"], m["off"], m["n_true"], m["n_false"]

	hdr = [
		"/* GENERATED by scripts/export_controller_c.py -- do not edit. */",
		f"/* source: {args.winner} */",
		"#ifndef WNN_MODEL_H",
		"#define WNN_MODEL_H",
		"#include <stdint.h>",
		"",
		f"#define WNN_NEURONS   {neurons}",
		f"#define WNN_BITS      {bits}",
		f"#define WNN_MOTORS    {motors}",
		f"#define WNN_LEVELS    {levels}",
		f"#define WNN_INPUT_BITS {in_bits}",
		# Feature geometry: the bench derives its thermometer walk from these
		# rather than hardcoding 15x8, so a model with a different observation
		# set benchmarks correctly instead of silently walking the wrong input.
		f"#define WNN_FEATURES  {int(nf)}",
		f"#define WNN_BITS_PER_FEATURE {int(bpf)}",
		f"#define WNN_NUM_KEYS  {len(keys)}",
		"",
		emit_array("wnn_conn", "uint8_t", list(out_conn), 24),
		emit_array("wnn_keys", "uint32_t", keys, 12),
		emit_array("wnn_off", "uint32_t", off, 16),
		"#endif /* WNN_MODEL_H */",
	]
	out = Path(args.out)
	out.parent.mkdir(parents=True, exist_ok=True)
	out.write_text("\n".join(hdr) + "\n")
	kb = (len(keys) * 4 + len(out_conn)) / 1024
	print(f"wrote {out}  neurons={neurons} bits={bits} in_bits={in_bits} "
	      f"features={int(nf)}x{int(bpf)} keys={len(keys)}  (~{kb:.0f} KB of .rodata)")
	print(f"  on-set filter: TRUE={n_true} dropped FALSE/other={n_false} "
	      f"({n_false / max(1, n_true + n_false):.1%} of populated cells)")


if __name__ == "__main__":
	main()
